import type { Metadata } from "next";
import "./globals.css";
import { Fira_Sans } from "next/font/google";
import clsx from "clsx";

const font = Fira_Sans({
  subsets: ["vietnamese"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx([font.className])}>{children}</body>
    </html>
  );
}
